name: Rust
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install ALSA
        run: sudo apt-get install libasound2-dev

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: rustfmt
        run: cargo fmt -- --check
        
      - name: clippy
        run: cargo clippy -- -D warnings && cargo clippy --tests -- -D warnings
        
      - name: test
        run: cargo test
